services:
  fastapi-telegram-bot-example:
    build:
      context: .
      args:
        PORT: 8080
        WORKDIR: "/fastapi-telegram-bot-example"
    ports:
      - "8080:8080"
    restart: unless-stopped